name: Lint

on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Run checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 18.X

      - name: Install deps
        run: npm install

      - name: Fix Lint Errors
        run: npm run lint:fix

      - name: Run Lint
        run: npm run lint:show
